name: "[Build] chromium-kiosk docker image"

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and push image
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ./Dockerfile
            platforms: linux/amd64,linux/arm64
            push: true
            build-args: |
              BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
            tags: |
              ghcr.io/pjswhite/chromium-kiosk:latest